### ISSUE TITLE
body-parser

### ISSUE THREAD

**Issue by vigneshwaran-chandrasekaran** [sridharrajs/nodejs-web-boilerplate#37]
do we need body-parser package for latest express above 4.16?

**Comment by sridharrajs** [comment]
> do we need body-parser package for latest express above 4.16?

No. We can use express to do it for us. 

Ref [Express 4.16.0 - Release date: 2017-09-28](https://expressjs.com/en/changelog/4x.html#4.16.0)

Thanks. Fixed
